# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name ForestRcpp
#' @title Fit a random forest for CDE
#'
#' @description Provides a wrapper to the C++ RFCDE implementation.
#'
#' @param x_train a matrix of training covariates.
#' @param z_basis a matrix of basis evaluations for training responses.
#' @param n_trees the number of trees in the forest.
#' @param mtry the number of candidate variables to try for each split.
#' @param node_size the minimum number of observations in a leaf node.
#'
#' @export ForestRcpp
NULL